title: AEC
#email: your-email@example.com
#description: 
#baseurl: #the subpath of your site,
#url: #the base hostname & protocol
#twitter_username: jekyllrb
#github_username: jekyll

#Build settings
#markdown: kramdown
#theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
